workflows:
  android-kiosk-launcher:
    name: Build Kiosk Launcher APK
    max_build_duration: 30
    environment:
      vars:
        # Optional: Set to true if you want to build a release version
        BUILD_RELEASE: false

        # Signing credentials (only needed for release builds)
        # These must be added in Codemagic > Environment variables (marked as secure)
        # CM_KEYSTORE: base64 encoded .jks file
        # CM_KEYSTORE_PASSWORD: keystore password
        # CM_KEY_PASSWORD: key password
        # CM_KEY_ALIAS: key alias

    scripts:
      - name: Decode keystore (only for release build)
        script: |
          if [ "$BUILD_RELEASE" = "true" ]; then
            echo $CM_KEYSTORE | base64 -d > /tmp/keystore.jks
          fi

      - name: Set Gradle wrapper permissions
        script: chmod +x ./gradlew

      - name: Build APK
        script: |
          if [ "$BUILD_RELEASE" = "true" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-mataslankauskas3@gmail.com  # optional: change or remove
