workflows:
  android-kiosk-launcher:
    name: Build Kiosk Launcher APK
    max_build_duration: 30

    environment:
      vars:
        BUILD_RELEASE: false

    machine:
      os: linux

    scripts:
      - name: Decode keystore (only if release)
        script: |
          if [ "$BUILD_RELEASE" = "true" ]; then
            echo "$CM_KEYSTORE" | base64 -d > /tmp/keystore.jks
          fi

      - name: Set Gradle wrapper permissions
        script: chmod +x ./gradlew

      - name: Build APK
        script: |
          if [ "$BUILD_RELEASE" = "true" ]; then
            ./gradlew assembleRelease
          else
            ./gradlew assembleDebug
          fi

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - mataslankauskas3@gmail.com
